### PR TITLE
K8SPS-63: add ps-operator

### PR DESCRIPTION
**Pull request by pooknull**
https://jira.percona.com/browse/K8SPS-63

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

**Review by tplavcic — CHANGES_REQUESTED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

**Review by nmarukovich — APPROVED** [review]

**Review by hors — APPROVED** [review]

**Pull request merged**
