### PR TITLE
EVEREST-793: first Everest version

### PR DESCRIPTION
**Pull request by michal-kralik**
Deploy first Everest version in dev environment

EVEREST-793

### CODE REVIEW

**Review by oksana-grishchenko — COMMENTED** [review]
Could you please elaborate why the `recommended` and `supported` sections are empty for 0.8.0 and what will be the normal process of adding a new version to the service?

**Comment by michal-kralik** [comment]
> Could you please elaborate why the `recommended` and `supported` sections are empty for 0.8.0 and what will be the normal process of adding a new version to the service?

They're empty because they're not needed in dev environment.
See dev vs. prod in https://github.com/Percona-Lab/percona-version-service?tab=readme-ov-file#how-to-publish-your-changes

It also describes the "normal" process of adding a version to the service.

**Review by oksana-grishchenko — APPROVED** [review]

**Comment by recharte** [comment]
> > Could you please elaborate why the `recommended` and `supported` sections are empty for 0.8.0 and what will be the normal process of adding a new version to the service?
> 
> They're empty because they're not needed in dev environment. See dev vs. prod in https://github.com/Percona-Lab/percona-version-service?tab=readme-ov-file#how-to-publish-your-changes
> 
> It also describes the "normal" process of adding a version to the service.

I'm still a bit confused, if they are not needed why do we need to have this file at all in dev? Can you please provide more details on how this will be used in dev vs prod?

**Comment by recharte** [comment]
> The version service runs in dev and prod deployments. We can use the dev deployment for integration tests without having to update the prod deployment.
> 
> At the moment the integration tests are stuck because they cannot retrieve the latest version of Everest. By deploying this change I hope to resolve part of the issues with integration tests.

Ok so you don't need the versions of the components yet, you just need to have an everest version present. I'm expecting that you will need to add the component versions soon though. It doesn't seem to make much sense to have a version without the component versions but since this will unblock you for the rest of the work I don't see any issues.

**Review by recharte — APPROVED** [review]

**Pull request merged**
