### PR TITLE
K8SPSMDB-794 psmdb release 1.14.0: fix operator hash

### PR DESCRIPTION
**Pull request by nmarukovich**

### CODE REVIEW

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

**Review by cap1984 — APPROVED** [review]

**Pull request merged**
